name: glitz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
 
  flutter_holo_date_picker: ^1.1.3
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  jiffy: ^6.3.1
  story_view: ^0.16.5
  uuid: ^4.4.2
  video_player: ^2.9.1

  #? for show in network image
  cached_network_image: ^3.4.0
  emoji_picker_flutter: ^2.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  lottie: ^3.1.2
  google_generative_ai: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/