// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBRJ5BK0y43JWoY2cnmDoADL4LLnXYNSs',
    appId: '1:1040172260122:android:795047c8bc42be494f2aa3',
    messagingSenderId: '1040172260122',
    projectId: 'glitz-b482b',
    storageBucket: 'glitz-b482b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXgdo4ETOGfT7jxQMgpQGWVaXic7SK1XI',
    appId: '1:1040172260122:ios:92c24d1e88a404e14f2aa3',
    messagingSenderId: '1040172260122',
    projectId: 'glitz-b482b',
    storageBucket: 'glitz-b482b.appspot.com',
    androidClientId: '1040172260122-aq0j3kfoqd2spbhmrl10ue66dn1v1lko.apps.googleusercontent.com',
    iosClientId: '1040172260122-k5eghlj34oe3j9oe93d7lus875j8vn01.apps.googleusercontent.com',
    iosBundleId: 'com.example.glitz',
  );

}